package notification

const ExtraFieldID = "id"
const ExtraFieldUserID = "user_id"
const ExtraFieldDriverName = "driver_name"
const ExtraFieldDriverID = "driver_id"
const ExtraFieldShipperName = "shipper_name"
const ExtraFieldOrderName = "order_name"
const ExtraFieldScheduleStatusKey = "schedule_status"
const ExtraFieldOrderID = "order_id"
const ExtraFieldOrderTotal = "order_total"
const ExtraFieldBookingID = "booking_id"
const ExtraFieldAvatarURL = "avatar_url"
const ExtraFieldTime = "time"
const ExtraFieldSOSName = "sos_name"
const ExtraFieldLocationStatus = "location_status"
const ExtraFieldWasExpired = "was_expired"
const ExtraFieldStatus = "status"
const ExtraFieldAcceptedRole = "accepted_role"
const ExtraFieldAcceptedAt = "accepted_at"
const ExtraFieldStartedAt = "started_at"
const ExtraFieldAssigneeName = "assignee_name"
const ExtraFieldTruckOperatorId = "truck_operator_id"
const ExtraFieldTruckOperatorName = "truck_operator_name"
const ExtraFieldUserRole = "user_role"
const ExtraFieldExpiryDate = "expiry_date"
